### ISSUE TITLE
Cannot run "./environment.swift ... ..." in command line

### ISSUE THREAD

**Issue by buzruk** [levochkaa/BetterTG#1]
brew install swift-sh
sudo chmod +x environment.swift
sudo chmod +x gyb.sh
./environment.swift <api_id> <api_hash>

**Result:**
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/buzurgmexr/Library/Developer/swift-sh.cache/06d1ad3029f464ec762d76ec9a1d0c91/main.swift:10:8: error: no such module 'ArgumentParser'
import ArgumentParser
       ^
/Users/buzurgmexr/Library/Developer/swift-sh.cache/06d1ad3029f464ec762d76ec9a1d0c91/main.swift:10:8: error: no such module 'ArgumentParser'
import ArgumentParser
       ^

error: 1 <(/usr/bin/swift build -Xswiftc -suppress-warnings)

**Comment by johnappleseed1973** [comment]
same here

**Comment by levochkaa** [comment]
@johnappleseed1973 @buzruk 
Sorry, for waiting for so long, didn't even know that someone gonna post an issue here, lol
And thanks for pointing this out. 

Should be fixed in 7d30a163290540871b7e368af771bb520fd372f4.
