### ISSUE TITLE
Group and channel supported?

### ISSUE THREAD

**Issue by zoujiaqing** [levochkaa/BetterTG#2]

**Comment by levochkaa** [comment]
nope

i've had some experiments with channels and groups, but they didn't come into any commits, as i remember. 
i am stuck at implementing nice user experience in just chatting.
and channels/groups aren't the priority atm, sorry

**Comment by levochkaa** [comment]
not an issue, but just a question, if you have any more question, text me in telegram https://levpoz.t.me
